### ISSUE TITLE
Unable to run in Eclipse using spring boot

### ISSUE THREAD

**Issue by Rajshah1897** [oktadeveloper/okta-secure-spring-rest-api-example#2]
Getting this error on my eclipse console when running in spring boot.

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://dev-361462.okta.com/oauth2/default/.well-known/openid-configuration": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Followed the steps upto Machine to Machine application. Don't know to how to go with open id connect website? is that required?

**Comment by bdemers** [comment]
It looks like you are using an old JVM?  Older JVMs (even old version of Java 1.8) do not support the current Root certificates)

Your best bet its to update to newer version of Java 1.8 (or newer).  I'd recommend using [SDKMAN](https://sdkman.io/)

**Comment by bdemers** [comment]
(if that doesn't work let us know, and we can reopen this issue)
